sudo: required
language: rust
rust:
  - nightly
  - beta
  - 1.1.0
env:
  global:
    - secure: EcBvxcEJTxVg89DF7hR/VqwsGanWnngimblVgwyLhy3bk2ApyxKOcmcuzMdXMttGUvzB2ua+8LefnoKrXRwJ8Ms+NeDdp60H7brzwFZM2CbAQiVr8Gkk0o7refonvHOapcECRYFNHoVcRRYVyw+AEqmzGTx8X39mYHH5t9G5YfQ=
install:
  - sudo apt-get install libtool autoconf
  - git clone https://github.com/anrieff/libcpuid.git && cd libcpuid
  - libtoolize
  - autoreconf --install
  - ./configure && make && sudo make install
  - sudo ldconfig
  - cd ..
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo bench
  - travis-cargo doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
  - travis-cargo coveralls
